CREATE DATABASE MY_REALISATION ;
USE MY_REALISATION ;
CREATE TABLE USER_MAN
(
 id_USER_MAN INT PRIMARY KEY AUTO_INCREMENT ,
 name_user VARCHAR(50) NOT NULL ,
 email VARCHAR(50) UNIQUE ,
 password_user VARCHAR(50) NOT NULL 
);
CREATE TABLE CATEGORIES
(
 id_CATEGORIES INT AUTO_INCREMENT PRIMARY KEY ,
 content_categories VARCHAR(100) NOT NULL 
);
CREATE TABLE POSTE
(
 id_POSTE INT AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(50) NOT NULL,
 content_post TEXT NOT NULL,
 id_user INT,
 id_categories INT,
 FOREIGN KEY (id_user) REFERENCES USER_MAN(id_USER_MAN),
 FOREIGN KEY (id_categories) REFERENCES CATEGORIES(id_CATEGORIES)
);
CREATE TABLE COMMENT_USER
(
 id_COMMENT_USER INT AUTO_INCREMENT PRIMARY KEY ,
 content TEXT NOT NULL ,
 date_comment DATE NOT NULL ,
 id_poste INT ,
 FOREIGN KEY (id_poste) REFERENCES POSTE(id_POSTE)
);
ALTER TABLE USER_MAN ADD INDEX idex_email (email);
ALTER TABLE USER_MAN ADD INDEX idex_name_user (name_user);
ALTER TABLE USER_MAN ADD INDEX idex_password_user (password_user);
ALTER TABLE CATEGORIES ADD INDEX idex_content_categories (content_categories);
ALTER TABLE POSTE ADD INDEX idex_title (title);
ALTER TABLE POSTE ADD INDEX idex_content_post (content_post(255));
ALTER TABLE COMMENT_USER ADD INDEX idex_content (content(255));
ALTER TABLE COMMENT_USER ADD INDEX idex_date_comment (date_comment);

ALTER TABLE USER_MAN COMMENT = 'Table des utilisateurs du blog';
ALTER TABLE COMMENT_USER COMMENT = 'Table des commentaires du blog';
ALTER TABLE POSTE COMMENT = 'Table des articles du blog';
ALTER TABLE CATEGORIES COMMENT = 'Table des categories du blog';