CREATE DATABASE MY_REALISATION ;
USE MY_REALISATION ;
CREATE TABLE USER_MAN
(
 id INT PRIMARY KEY AUTO_INCREMENT ,
 name_user VARCHAR(50) NOT NULL ,
 email VARCHAR(50) UNIQUE ,
 password_user VARCHAR(50) NOT NULL 
);
CREATE TABLE CATEGORIES
(
 id INT AUTO_INCREMENT PRIMARY KEY ,
 content_categories VARCHAR(100) NOT NULL 
);
CREATE TABLE POSTE
(
 id INT AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(50) NOT NULL,
 content_post TEXT NOT NULL,
 id_user INT,
 id_categories INT,
 FOREIGN KEY (id_user) REFERENCES USER_MAN(id),
 FOREIGN KEY (id_categories) REFERENCES CATEGORIES(id)
);
CREATE TABLE COMMENT_USER
(
 id INT AUTO_INCREMENT PRIMARY KEY ,
 content TEXT NOT NULL ,
 date_comment DATE NOT NULL ,
 id_poste INT ,
 FOREIGN KEY (id_poste) REFERENCES POSTE(id)
);