CREATE DATABASE MY_PROJECT ;
USE MY_PROJECT ;
CREATE TABLE USER_MAN
(
 id_USER_MAN INT PRIMARY KEY AUTO_INCREMENT ,
 name_user VARCHAR(50) NOT NULL ,
 email VARCHAR(50) UNIQUE ,
 password_user VARCHAR(50) NOT NULL 
);
CREATE TABLE CATEGORIES
(
 id_CATEGORIES INT AUTO_INCREMENT PRIMARY KEY ,
 content_categories VARCHAR(100) NOT NULL 
);
CREATE TABLE ARTICLE
(
 id_ARTICLE INT AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(50) NOT NULL,
 content_post TEXT NOT NULL,
 id_user INT,
 id_categories INT,
 FOREIGN KEY (id_user) REFERENCES USER_MAN(id_USER_MAN),
 FOREIGN KEY (id_categories) REFERENCES CATEGORIES(id_CATEGORIES)
);
CREATE TABLE COMMENT_USER
(
 id_COMMENT_USER INT AUTO_INCREMENT PRIMARY KEY ,
 content TEXT NOT NULL ,
 date_comment DATE NOT NULL ,
 id_poste INT ,
 FOREIGN KEY (id_poste) REFERENCES ARTICLE(id_ARTICLE)
);
ALTER TABLE POSTE ADD INDEX idex_content_post (content_post(255));
ALTER TABLE COMMENT_USER ADD INDEX idex_content (content(255));
ALTER TABLE COMMENT_USER ADD INDEX idex_date_comment (date_comment);